[global-dns]  
resolve-mode=exclusive  

# Use Andrews & Arnold's unfiltered DoT upstream (we block ads using
# the 70-pinehole.sh script that generates zz-pinehole.conf)
# See: https://mullvad.net/en/help/dns-over-https-and-dns-over-tls
[global-dns-domain-*]  
servers=dns+tls://[2001:8b0::2022]@853#dns.aa.net.uk,dns+tls://[2001:8b0::2023]@853#dns.aa.net.uk
