[global-dns]  
resolve-mode=exclusive  

# Forward queries to Mullvad's ad & malware blocking DNS upstream
# See: https://mullvad.net/en/help/dns-over-https-and-dns-over-tls
[global-dns-domain-*]  
servers=dns+tls://2a07:e340::4@853#base.dns.mullvad.net
