# This file is named with a zz- prefix to ensure
# it takes precedence (i.e. is loaded last and
# overwrites) the config written by dnsconfd into
# /etc/unbound/conf.d/unbound.conf.
#
# This is important because dnsconfd does not
# support dns64 and treats the module-config
# line very statically.

server:
    # Configure DNS64 to synthesise NAT64 addresses (while still validating DNSSEC)
    # We can test that DNSSEC still works under this config at: https://dnscheck.tools
    module-config: "dns64 validator iterator"
    # This is the prefix used by AAISP
    dns64-prefix: 2001:8b0:6464:0:66::/96
